apiVersion: v1
kind: Service
metadata:
  name: mouse-reviews
  labels:
    app: mouse-reviews
    version: v1
spec:
  ports:
    - port: 8081
      name: http
      targetPort: 8080
  selector:
    app: mouse-reviews
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mouse-reviews
    version: v1
  name: mouse-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mouse-reviews
      version: v1
  template:
    metadata:
      labels:
        app: mouse-reviews
        version: v1
    spec:
      containers:
        - name: mouse-reviews
          image: mouse-reviews:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTIONS
              value: -Xms15m -Xmx15m -Xmn15m
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: APP_SIMULATED_ERROR_POSSIBILITY_PERCENT
              value: "50"
