spring:
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: transferRequests
        process-out-0:
          destination: transferResults

bank:
  name: BANK1
server:
  port: 9181
