apiVersion: v1
kind: Namespace
metadata:
  name: mini-app
  labels:
    name: mini-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mini-app
  name: mini
  labels:
    app: mini
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mini
  template:
    metadata:
      name: mini
      labels:
        app: mini
    spec:
      containers:
        - name: mini
          image: mini:v1
          env:
            - name: JAVA_OPTIONS
              value: -Xmx15M
          imagePullPolicy: Never
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: mini-app
  name: mini
spec:
  selector:
    app: mini
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
