# Common configuration
server.port:
  8087

spring:
  cloud:
    stream:
      bindings:
        revertPayment-in-0:
          destination: cancelled-orders
          group: payment
  liquibase:
    change-log: classpath:db/changelog/db.changelog-payment.xml
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  application:
    name: payment-service

# Profile-specific configuration
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:payments

---
spring:
  config:
    activate:
      on-profile: database-per-service
  datasource:
    url: jdbc:h2:~/data/payments;AUTO_SERVER=TRUE

---
spring:
  config:
    activate:
      on-profile: shared-database
  datasource:
    url: jdbc:h2:tcp://h2-server:1521/opt/h2-data/laptop_store
  h2:
    console:
      enabled: false
