= Обработка ошибок в SCS

Здесь мы демонстрируем обработку ошибок в Spring Cloud Stream.

Если обработчик сообщений выбрасывает исключение, доставка сообщения повторяется в соответствии с конфигурацией повторных попыток.

Мы имитируем ошибку, выбрасывая исключение в обработчике сообщений:

[source,java]
----
@Bean
public Consumer<Message<String>> process() {
    return message -> {
        System.out.println("Получено сообщение: " + message.getPayload());
        saveToDatabase(message.getPayload());
    };
}

private void saveToDatabase(String payload) {
    throw new RuntimeException("База данных недоступна");
}
----

Предположим, что база данных временно недоступна, и мы не можем сохранить сообщение. Нам нужно, чтобы оно было повторно отправлено позже, когда база данных снова будет работать.

По умолчанию сообщение повторно отправляется 3 раза. Интервал между попытками составляет 1000 мс. После каждой попытки интервал удваивается.

При необходимости можно настроить поведение повторных попыток.

Конфигурация задаётся в *application.yml* в *Subscriber*:

[source,yaml]
----
consumer:
  back-off-initial-interval: 1000
  back-off-max-interval: 100000
  back-off-multiplier: 2
  max-attempts: 10
  default-retryable: true
  retryable-exceptions:
    java.lang.RuntimeException: true
----

Здесь мы задаем:

* *back-off-initial-interval* – интервал между первой и второй попыткой
* *back-off-max-interval* – максимальный интервал между попытками
* *back-off-multiplier* – каждая следующая задержка умножается на это значение
* *max-attempts* – максимальное количество попыток
* *default-retryable* – если true, все исключения будут повторно обработаны
* *retryable-exceptions* – список исключений, которые можно повторно обработать (по умолчанию все исключения повторно обрабатываются)

Если сообщение не будет доставлено после последней попытки, оно отправляется в *DLQ* (Dead Letter Queue), если он настроен.

DLQ настраивается в *application.yml* в *Subscriber*:

[source,yaml]
----
consumer:
  dlq:
    enable-dlq: true
    dlq-name: wordStreamErrorsDLQ
----

Здесь мы включаем *DLQ* и задаем имя топика для *DLQ* – *wordStreamErrorsDLQ*.

*DLQ* – это отдельный топик, куда отправляются сообщения, которые не удалось доставить.

Сообщения попадают в *DLQ*, так как могут быть "ядовитыми" (всегда приводить к сбою приложения) и не должны повторяться.

*DLQ* должен контролироваться, а сообщения в нем обрабатываться вручную.